export const conferences = [
  {
    id: "1",
    name: "TechConnect 2025",
    date: "April 10-12, 2025",
    location: "San Francisco, CA",
    description:
      "Join the largest tech conference on the West Coast, featuring keynotes from industry leaders, hands-on workshops, and networking opportunities.",
    category: "it",
    status: "Upcoming",
    attendees: 1500,
    image: "/uploads/test.jpg",
    hashtags: ["tech", "innovation", "ai", "networking", "cloud"],
  },
  {
    id: "2",
    name: "CyberSec Summit",
    date: "April 15-17, 2025",
    location: "Washington, DC",
    description:
      "The premier cybersecurity conference bringing together security professionals, researchers, and policy makers to address the latest threats and solutions.",
    category: "security",
    status: "Upcoming",
    attendees: 1200,
    image: "/placeholder.svg?height=400&width=800",
    hashtags: ["cybersecurity", "hacking", "privacy", "infosec", "zerotrust"],
  },
  {
    id: "3",
    name: "DevCon 2025",
    date: "April 22-24, 2025",
    location: "Austin, TX",
    description:
      "A conference by developers, for developers. Learn about the latest programming languages, frameworks, and best practices.",
    category: "programming",
    status: "Upcoming",
    attendees: 2000,
    image: "/placeholder.svg?height=400&width=800",
    hashtags: ["coding", "webdev", "javascript", "react", "fullstack"],
  },
  {
    id: "4",
    name: "AI Innovation Forum",
    date: "May 5-7, 2025",
    location: "Boston, MA",
    description:
      "Explore the cutting edge of artificial intelligence and machine learning with researchers and practitioners from around the world.",
    category: "it",
    status: "Upcoming",
    attendees: 1000,
    image: "/placeholder.svg?height=400&width=800",
    hashtags: ["ai", "machinelearning", "deeplearning", "nlp", "computervision"],
  },
  {
    id: "5",
    name: "Cloud Computing Expo",
    date: "May 12-14, 2025",
    location: "Seattle, WA",
    description:
      "Discover the latest advancements in cloud technologies, serverless architecture, and infrastructure as code from leading cloud providers.",
    category: "it",
    status: "Upcoming",
    attendees: 1800,
    image: "/placeholder.svg?height=400&width=800",
    hashtags: ["cloud", "aws", "azure", "serverless", "devops"],
  },
  {
    id: "6",
    name: "Web Development Summit",
    date: "June 3-5, 2025",
    location: "Chicago, IL",
    description:
      "A comprehensive conference covering frontend, backend, and full-stack development with workshops on the latest web technologies.",
    category: "programming",
    status: "Upcoming",
    attendees: 1300,
    image: "/placeholder.svg?height=400&width=800",
    hashtags: ["webdev", "frontend", "backend", "javascript", "css"],
  },
]
